name: build
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - run: npm install
      - run: npm run build
