name: build
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - run: npm install
      - run: npm run build
