name: build-and-deploy
on:
  pull_request:
    branches:
    - deploy
    types:
    - closed
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.KUSIONSTACK_BOT_TOKEN }}
          external_repository: KusionStack/kusionstack.github.io
          publish_dir: ./build
          publish_branch: main
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
